name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
            echo "Hello World!"
            echo "Hello Praneeth I m new here"
      - name: print goodbye
        run: echo "Done- bye"
          
